Fix serialization errors for Dispatcher.jl
invenia/DeferredFutures.jl pull request #14
Opened 2017-07-17 19:07 UTC by nicoleepp

This is a fix for issue invenia/Dispatcher.jl#21

A new version of DeferredFutures should probably be released once this has merged so that Dispatcher.jl can reference that and avoid build failures.

I also got rid of the deprecated warnings that show up on Julia 0.6

2017-07-17 23:06 UTC, rofinn commented on src/DeferredFutures.jl
> +    Base.Serializer.serialize_cycle(s, ref) && return
Maybe there should be a simplified test which checks that the `serialize_cycle(s, ref) && return` solves the issue discovered in Dispatcher?

2017-07-18 00:08 UTC, nicoleepp commented on src/DeferredFutures.jl
> +    Base.Serializer.serialize_cycle(s, ref) && return
I'm not sure how to test that without adding Dispatcher.jl as a dependency for tests, which might be a good idea. I'll try that tomorrow.

2017-07-18 16:56 UTC, rofinn commented
Looks like the mac 0.5 build hit the HDF5 issue. [PR 430](https://github.com/JuliaIO/HDF5.jl/pull/430) should fix it once it gets merged and a new release is tagged.

2017-07-18 17:44 UTC, rofinn requested changes

2017-07-18 17:44 UTC, rofinn commented on test/REQUIRE
> +Dispatcher
Might want to specify a minimum version number.

2017-07-18 17:44 UTC, rofinn commented on test/runtests.jl
> +                results = run!(exec, ctx)
Should probably test that this actually returns 3 (vs a wrapped exception or something). Also, I'm a little worried about the DeferredFuture tests depending on dispatcher. Couldn't we just trigger this behaviour by passing a nested `DeferredFuture` between two processes (using `@spawn` directly)?

2017-07-18 18:22 UTC, nicoleepp commented on test/runtests.jl
> +                results = run!(exec, ctx)
You mean like this?

```using DeferredFutures
addprocs(2)
@everywhere using DeferredFutures

df = DeferredFuture()

@spawn begin
    df2 = DeferredFuture()
    put!(df2, 3)
    put!(df, df2)
end

@assert fetch(fetch(df)) == 3```

This seems to work fine. I've tried recreating the error without using Dispatcher but haven't been able to yet.

2017-07-18 20:24 UTC, rofinn commented on test/runtests.jl
> +                results = run!(exec, ctx)
Hmmm, yeah, I'm not entirely sure either. Did a bit of digging though and you could probably adapt the base julia tests for serialization cycles https://github.com/JuliaLang/julia/blob/master/test/serialize.jl#L350 ?

2017-07-18 20:28 UTC, nicoleepp commented on test/runtests.jl
> +                results = run!(exec, ctx)
Ok I will look into doing that

2017-07-19 19:24 UTC, nicoleepp commented on src/DeferredFutures.jl
> +    Base.Serializer.serialize_cycle(s, ref) && return
Finally figured out how to recreate the error that manifests itself in Dispatcher.jl. Tests have been updated.

2017-07-19 19:47 UTC, rofinn approved these changes
Nice work!

2017-07-19 19:47 UTC, rofinn commented on src/DeferredFutures.jl
> +    Base.Serializer.serialize_cycle(s, ref) && return
Awesome, thank you.

2017-07-19 19:47 UTC, rofinn commented on test/runtests.jl
> +        @testset "DeferredFuture serialization as part of another object" begin
Yeah, these tests look a lot cleaner now. It's also nice that it clearly documents the old failure condition outside of dispatcher.

2017-07-19 20:25 UTC, merged

2017-07-19 21:04 UTC, iamed2 commented
Great work!